version: '3.8'

services:
  # mcpo HTTP-Proxy für Weather Service
  weather-proxy:
    build:
      context: ./weather-service
      dockerfile: Dockerfile.mcpo
    ports:
      - "8007:8000"
    command: ["mcpo", "--", "python", "/app/run_server.py"]
    networks:
      - mcp-network
    container_name: mcp-weather-proxy
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # mcpo HTTP-Proxy für Mensa Service  
  mensa-proxy:
    build:
      context: ./mensa-service  
      dockerfile: Dockerfile.mcpo
    ports:
      - "8008:8000"
    command: ["mcpo", "--", "python", "/app/run_server.py"]
    networks:
      - mcp-network
    container_name: mcp-mensa-proxy
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  mcp-network:
    driver: bridge

volumes:
  weather-logs:
    driver: local
  mensa-logs:
    driver: local
